# ZSOZSO Project Configuration
# Official Stellar Info File
# https://zsozso.info

ACCOUNTS=[
  "GDZKLEYJ54QUIEYE4DUUOCIJDUS7R5MDW5MCAB3XTUGPJ3C7SSZJRQUC", # Issuer Account (Locked)
  "GAJLLU4LAOJ4Z2422BLMKGEBEGITXFLZTES5XGIHJLE55FSAJ6ZV3OUN", # Arthur Pendragon - Distribution Account - Project Owner
  "GA3QNFDIP325GNHKOR74JM3JVICK6V26W7LH3BYEXXTFJJPY6EDANTLC", # Merlin
  "GCA4CDNJMBYRO2CCC4RXICAR2IDVQ2TO7LYRFMGKSEK64L2WH6UZYN2H", # ifinta - Public Outreach
  "GBBD7MR7HJT2DQ4663H3VVTRYN4UZHQW26L3PZYRMRRU67Z2ZYI7UXEV", # for the Antarctica
  "GBRJVOSIPJV54N2NJ5NYKEVWNHQSOIRSOFN5RF5D4KQLU7YFZBZ325XS"  # for the ZSuPSZ (ZSOZSO Payment System)
]

VERSION="2.0.0" # The version of this toml file
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

# SEP-10 endpoint
WEB_AUTH_ENDPOINT="https://zsozso.info/auth"
SIGNING_KEY="GDWDIKGZUYZTTIR3PL67EGTKYVNZHBZHHX7XII3F7Z5JLK3XFF5CAPYJ"

[DOCUMENTATION]
ORG_NAME="Vortexledger"
ORG_URL="https://zsozso.info"
ORG_DESCRIPTION="A distributed community. Origo: Antarctica. Check the pictures on OUR Homepage"
ORG_PHYSICAL_ADDRESS="Gaia, the living planet"
ORG_LOGO="https://zsozso.info/icon.a910d4bd.png"
ORG_OFFICIAL_EMAIL="ifinta@mail.com"

# this is my private twitter account, Vortexledger using bksy officially: https://bsky.app/profile/zsozsoonstellar.bsky.social

ORG_TWITTER="ifinta66"

# this is THE official Telegram account of OUR Organization.

ORG_TELEGRAM="https://t.me/cyberforint"

[[PRINCIPALS]]
name="Arthur Pendragon"
ROLE="Project Owner & a REAL King & Chief Distribution Officer (CDO)"
ID="GAJLLU4LAOJ4Z2422BLMKGEBEGITXFLZTES5XGIHJLE55FSAJ6ZV3OUN" # Arthur Pendragon on the Stellar

[[PRINCIPALS]]
name="Merlin"
ROLE="The Wizard"
ID="GA3QNFDIP325GNHKOR74JM3JVICK6V26W7LH3BYEXXTFJJPY6EDANTLC" # actual account of Merlin

# me
[[PRINCIPALS]]
name="Istvan Finta"
ROLE="Public Relations & Internet Presence & more ... much more."
ID="GCA4CDNJMBYRO2CCC4RXICAR2IDVQ2TO7LYRFMGKSEK64L2WH6UZYN2H" # actual one
email="ifinta@mail.com"
github="ifinta"
twitter="ifinta66"

# this is THE official Telegram of OUR Organization.

telegram="https://t.me/cyberforint"

[[PRINCIPALS]]
name="Tattypoo"
ROLE="The good witch of the Nord, from the Tale"

[[PRINCIPALS]]
name="H"
ROLE="Key Test Manager from Miami Beach, Florida, US"

[[PRINCIPALS]]
name="Oz"
ROLE="The biggest Wizard from the Tale."
ID="GBYTEPIJG2UTJLLZVAPFG6D3JMOKB4REVHO5LFLLLCFZ4DL7MN3RSHVE" # the last one Stellar account of Oz

# exists more principals, but I must to do also some test and development today. Sorry.

[[CURRENCIES]]
code="ZSOZSO"
issuer="GDZKLEYJ54QUIEYE4DUUOCIJDUS7R5MDW5MCAB3XTUGPJ3C7SSZJRQUC"
contract_id="CB3E6DIKOKXF4VYV3ALGS5Z2JWZ43Q24XEAX4QLV2ZC5SLGNSRWNHP6F"
anchor_asset_type="other"
display_decimals=7
image="https://zsozso.info/icon.a910d4bd.png"
name="ZSOZSO"
desc="Vortexledger community asset"
is_asset_anchored=false
status="live"

#[[VALIDATORS]]
#ALIAS="Halas"
#DISPLAY_NAME="Halas"
#HOST="TBD - https://zsozso.info/halas + redirect?"
#PUBLIC_KEY="GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7"
#HISTORY="TBD - an URL"

# near term targets:
METADATA_GOAL_NODE="Saját magyarországi Validator Node (Halas) or NODEs... indítása folyamatban. Also a Hungarian Testnet. ... Partnereket keresünk! MNB? OTP? MOL? I will ask they also ASAP!!! Read, please: https://zsozso.info/opentasks.html"
METADATA_NODE_IDENTITY="GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7"
METADATA_NODE_STATUS="Infrastructure migration in progress - Halas Node (Hungary) planned to resume."

# hints about working contracts - we hope - check, use it, please:
METADATA_VAULT_3DAY="CBW6S2YN2PLVHRWGPP4J3WUZH2WFQRSVGW3MPPUVUIMUFQTAT4CD" # A public 3-days Escrow Vault for ZSOZSO. Use it please. Use it and forget Your ZSOZSO. Such simple :D DM me on bitcointalk.org, if it is better as documented HERE, and it was well usable for You - 1000 ZSOZSO bounty per prooved usage!! ;D It is a safe safe - Oz developed it and we TRUST Oz. Is it an issue? I checked it brifly also.
METADATA_VAULT_30_60DAY="CBACZX45CAIFMG3O5EM4XIS37SFTZEQSOYMWNHV5ZCY2LQ6IPRHEGMB6" # A public 30..60-days Escrow Vault for ZSOZSO. Use it please. Use it and forget Your ZSOZSO. Such simple :D DM me on bitcointalk.org, if it is better as documented HERE, and it was well usable for You - 2000 ZSOZSO bounty per prooved usage!! ;D
METADATA_VAULT_1_2YEARS="CBDQH2TF3KUPZMALUJKMFDW6L2VJWUXS4KXPYVOE35FT6P7FUMBTRK4G" # A public Escrow Vault (1-2 YEARS) for ZSOZSO. Use it please. Use it and forget Your ZSOZSO. Such simple :D DM me on bitcointalk.org, if it is better as documented on Stellar Mainnet, and it was well usable for You - 3000 ZSOZSO bounty per prooved usage!! ;D

# Remark to community (to the Hungarian community)
[NOTICES]
TEXT="A projekt múltbeli biztonsági incidensek miatt szigorított account-kezelést alkalmaz."
